export default {
    //更新合约列表
    SET_CONTRACT_TEMPLATE_LIST: "SET_CONTRACT_TEMPLATE_LIST",
    SET_CONTRACT_TEMPLATE_LIST_IN_OUT_MODULE:"contractTemplate/SET_CONTRACT_TEMPLATE_LIST",

    //合约模板版本列表
    SET_TEMPLATE_VERSION_LIST: "SET_TEMPLATE_VERSION_LIST",
    SET_TEMPLATE_VERSION_LIST_IN_OUT_MODELE:"contractTemplate/SET_TEMPLATE_VERSION_LIST"
}